name: E2E tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      playwright:
        image: "mcr.microsoft.com/playwright:v1.55.0-noble"
        ports:
          - "3000:3000"
        options: >-
          --init
          -it
          --workdir /home/pwuser
          --user pwuser
          -c 'npx -y playwright@1.55.0 run-server --port 3000 --host 0.0.0.0'
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build

      - name: Run Playwright tests
        run: pnpm run test:e2e --shard=${{ matrix.shard }}
